name: mini_e_learning
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  dio: ^5.1.1
  form_builder_validators: ^8.4.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  flutter_widget_from_html: ^0.9.1
  shimmer: ^2.0.0
  cloud_firestore: ^4.5.0
  timeago: ^3.3.0
  flutter_screenutil: ^5.7.0
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/

flutter_native_splash:
  color: "#3A7FD5"
  image: assets/img/favicon.png
  android: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/img/favicon.png"
  min_sdk_android: 19
  adaptive_icon_background: "#3A7FD5"
  adaptive_icon_foreground: "assets/img/favicon.png"
